/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyIndexRouteImport } from './routes/apply.index'
import { Route as TrackingAppIdRouteImport } from './routes/tracking.$appId'
import { Route as ApplyAppIdRouteImport } from './routes/apply.$appId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ApiPublicCatboxUploadRouteImport } from './routes/api/public/catbox.upload'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/apply/',
  path: '/apply/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingAppIdRoute = TrackingAppIdRouteImport.update({
  id: '/tracking/$appId',
  path: '/tracking/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyAppIdRoute = ApplyAppIdRouteImport.update({
  id: '/apply/$appId',
  path: '/apply/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicCatboxUploadRoute = ApiPublicCatboxUploadRouteImport.update({
  id: '/api/public/catbox/upload',
  path: '/api/public/catbox/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/officer': typeof OfficerRoute
  '/queue': typeof QueueRoute
  '/register': typeof RegisterRoute
  '/admin/users': typeof AdminUsersRoute
  '/apply/$appId': typeof ApplyAppIdRoute
  '/tracking/$appId': typeof TrackingAppIdRoute
  '/apply/': typeof ApplyIndexRoute
  '/api/public/catbox/upload': typeof ApiPublicCatboxUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/officer': typeof OfficerRoute
  '/queue': typeof QueueRoute
  '/register': typeof RegisterRoute
  '/admin/users': typeof AdminUsersRoute
  '/apply/$appId': typeof ApplyAppIdRoute
  '/tracking/$appId': typeof TrackingAppIdRoute
  '/apply': typeof ApplyIndexRoute
  '/api/public/catbox/upload': typeof ApiPublicCatboxUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/officer': typeof OfficerRoute
  '/queue': typeof QueueRoute
  '/register': typeof RegisterRoute
  '/admin/users': typeof AdminUsersRoute
  '/apply/$appId': typeof ApplyAppIdRoute
  '/tracking/$appId': typeof TrackingAppIdRoute
  '/apply/': typeof ApplyIndexRoute
  '/api/public/catbox/upload': typeof ApiPublicCatboxUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/officer'
    | '/queue'
    | '/register'
    | '/admin/users'
    | '/apply/$appId'
    | '/tracking/$appId'
    | '/apply/'
    | '/api/public/catbox/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/officer'
    | '/queue'
    | '/register'
    | '/admin/users'
    | '/apply/$appId'
    | '/tracking/$appId'
    | '/apply'
    | '/api/public/catbox/upload'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/officer'
    | '/queue'
    | '/register'
    | '/admin/users'
    | '/apply/$appId'
    | '/tracking/$appId'
    | '/apply/'
    | '/api/public/catbox/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OfficerRoute: typeof OfficerRoute
  QueueRoute: typeof QueueRoute
  RegisterRoute: typeof RegisterRoute
  ApplyAppIdRoute: typeof ApplyAppIdRoute
  TrackingAppIdRoute: typeof TrackingAppIdRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
  ApiPublicCatboxUploadRoute: typeof ApiPublicCatboxUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/': {
      id: '/apply/'
      path: '/apply'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/$appId': {
      id: '/tracking/$appId'
      path: '/tracking/$appId'
      fullPath: '/tracking/$appId'
      preLoaderRoute: typeof TrackingAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$appId': {
      id: '/apply/$appId'
      path: '/apply/$appId'
      fullPath: '/apply/$appId'
      preLoaderRoute: typeof ApplyAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/catbox/upload': {
      id: '/api/public/catbox/upload'
      path: '/api/public/catbox/upload'
      fullPath: '/api/public/catbox/upload'
      preLoaderRoute: typeof ApiPublicCatboxUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OfficerRoute: OfficerRoute,
  QueueRoute: QueueRoute,
  RegisterRoute: RegisterRoute,
  ApplyAppIdRoute: ApplyAppIdRoute,
  TrackingAppIdRoute: TrackingAppIdRoute,
  ApplyIndexRoute: ApplyIndexRoute,
  ApiPublicCatboxUploadRoute: ApiPublicCatboxUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
