/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyIndexRouteImport } from './routes/apply.index'
import { Route as TrackingAppIdRouteImport } from './routes/tracking.$appId'
import { Route as ApplyAppIdRouteImport } from './routes/apply.$appId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminAuditTrailRouteImport } from './routes/admin.audit-trail'
import { Route as OfficerAuditTrailRouteImport } from './routes/officer.audit-trail'
import { Route as ApiPublicStripeVerifyRouteImport } from './routes/api.public.stripe.verify'
import { Route as ApiPublicStripeCreateSessionRouteImport } from './routes/api.public.stripe.create-session'
import { Route as ApiPublicCatboxUploadRouteImport } from './routes/api.public.catbox.upload'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/apply/',
  path: '/apply/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingAppIdRoute = TrackingAppIdRouteImport.update({
  id: '/tracking/$appId',
  path: '/tracking/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyAppIdRoute = ApplyAppIdRouteImport.update({
  id: '/apply/$appId',
  path: '/apply/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditTrailRoute = AdminAuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => AdminRoute,
} as any)
const OfficerAuditTrailRoute = OfficerAuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => OfficerRoute,
} as any)
const ApiPublicStripeVerifyRoute = ApiPublicStripeVerifyRouteImport.update({
  id: '/api/public/stripe/verify',
  path: '/api/public/stripe/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeCreateSessionRoute =
  ApiPublicStripeCreateSessionRouteImport.update({
    id: '/api/public/stripe/create-session',
    path: '/api/public/stripe/create-session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCatboxUploadRoute = ApiPublicCatboxUploadRouteImport.update({
  id: '/api/public/catbox/upload',
  path: '/api/public/catbox/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/officer': typeof OfficerRouteWithChildren
  '/queue': typeof QueueRoute
  '/register': typeof RegisterRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/audit-trail': typeof AdminAuditTrailRoute
  '/officer/audit-trail': typeof OfficerAuditTrailRoute
  '/apply/$appId': typeof ApplyAppIdRoute
  '/tracking/$appId': typeof TrackingAppIdRoute
  '/apply/': typeof ApplyIndexRoute
  '/api/public/catbox/upload': typeof ApiPublicCatboxUploadRoute
  '/api/public/stripe/create-session': typeof ApiPublicStripeCreateSessionRoute
  '/api/public/stripe/verify': typeof ApiPublicStripeVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/officer': typeof OfficerRouteWithChildren
  '/queue': typeof QueueRoute
  '/register': typeof RegisterRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/audit-trail': typeof AdminAuditTrailRoute
  '/officer/audit-trail': typeof OfficerAuditTrailRoute
  '/apply/$appId': typeof ApplyAppIdRoute
  '/tracking/$appId': typeof TrackingAppIdRoute
  '/apply': typeof ApplyIndexRoute
  '/api/public/catbox/upload': typeof ApiPublicCatboxUploadRoute
  '/api/public/stripe/create-session': typeof ApiPublicStripeCreateSessionRoute
  '/api/public/stripe/verify': typeof ApiPublicStripeVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/officer': typeof OfficerRouteWithChildren
  '/queue': typeof QueueRoute
  '/register': typeof RegisterRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/audit-trail': typeof AdminAuditTrailRoute
  '/officer/audit-trail': typeof OfficerAuditTrailRoute
  '/apply/$appId': typeof ApplyAppIdRoute
  '/tracking/$appId': typeof TrackingAppIdRoute
  '/apply/': typeof ApplyIndexRoute
  '/api/public/catbox/upload': typeof ApiPublicCatboxUploadRoute
  '/api/public/stripe/create-session': typeof ApiPublicStripeCreateSessionRoute
  '/api/public/stripe/verify': typeof ApiPublicStripeVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/officer'
    | '/queue'
    | '/register'
    | '/admin/users'
    | '/admin/audit-trail'
    | '/officer/audit-trail'
    | '/apply/$appId'
    | '/tracking/$appId'
    | '/apply/'
    | '/api/public/catbox/upload'
    | '/api/public/stripe/create-session'
    | '/api/public/stripe/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/officer'
    | '/queue'
    | '/register'
    | '/admin/users'
    | '/admin/audit-trail'
    | '/officer/audit-trail'
    | '/apply/$appId'
    | '/tracking/$appId'
    | '/apply'
    | '/api/public/catbox/upload'
    | '/api/public/stripe/create-session'
    | '/api/public/stripe/verify'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/officer'
    | '/queue'
    | '/register'
    | '/admin/users'
    | '/admin/audit-trail'
    | '/officer/audit-trail'
    | '/apply/$appId'
    | '/tracking/$appId'
    | '/apply/'
    | '/api/public/catbox/upload'
    | '/api/public/stripe/create-session'
    | '/api/public/stripe/verify'
  fileRoutesByFullPath: FileRoutesByFullPath
}

declare module '@tanstack/react-router' {
  interface FileRouteTypes extends FileRouteTypes {}
}

const AdminRouteChildren = [AdminUsersRoute, AdminAuditTrailRoute] as const
const AdminRouteWithChildren = AdminRoute.addChildren(AdminRouteChildren)

const OfficerRouteChildren = [OfficerAuditTrailRoute] as const
const OfficerRouteWithChildren = OfficerRoute.addChildren(OfficerRouteChildren)

export const routeTree = rootRouteImport.addChildren([
  IndexRoute,
  AdminRouteWithChildren,
  DashboardRoute,
  LoginRoute,
  OfficerRouteWithChildren,
  QueueRoute,
  RegisterRoute,
  ApplyAppIdRoute,
  TrackingAppIdRoute,
  ApplyIndexRoute,
  ApiPublicCatboxUploadRoute,
  ApiPublicStripeCreateSessionRoute,
  ApiPublicStripeVerifyRoute,
])
